Log:
  Level: none # Cấp độ nhật ký: không có, lỗi, cảnh báo, thông tin, gỡ lỗi
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Đường dẫn đến cấu hình dns, check https://xtls.github.io/config/dns.html để được giúp đỡ
RouteConfigPath: # /etc/XrayR/route.json # Đường dẫn đến cấu hình định tuyến, check https://xtls.github.io/config/routing.html để được giúp đỡ
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Đường dẫn đến cấu hình gửi đến tùy chỉnh, check https://xtls.github.io/config/inbound.html để được giúp đỡ
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Đường dẫn đến cấu hình gửi đi tùy chỉnh, check https://xtls.github.io/config/outbound.html để được giúp đỡ
ConnetionConfig:
  Handshake: 4 # Giới hạn thời gian bắt tay, Thứ hai
  ConnIdle: 30 # Giới hạn thời gian không hoạt động của kết nối, Thứ hai
  UplinkOnly: 2 # Giới hạn thời gian khi kết nối hạ lưu bị đóng, Thứ hai
  DownlinkOnly: 4 # Giới hạn thời gian khi kết nối bị đóng sau khi đường lên được đóng, Thứ hai
  BufferSize: 64 # Kích thước bộ nhớ đệm bên trong của mỗi kết nối, kB
Nodes:
  -
    PanelType: "V2board" # Loại bảng điều khiển: SSpanel, V2board, PMpanel, , Proxypanel
    ApiConfig:
      ApiHost: "https://daudau02.tk"
      ApiKey: "key" # key liên kết với web
      NodeID: 1 # ID của nút server 
      NodeType: V2ray # Loại nút: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Thời gian chờ cho yêu cầu api
      EnableVless: false # Bật Vless cho loại V2ray
      EnableXTLS: false # Bật XTLS cho V2ray và Trojan
      SpeedLimit: 0 # Mbps, Cài đặt cục bộ sẽ thay thế cài đặt từ xa, 0 nghĩa là tắt
      DeviceLimit: 10 # Cài đặt cục bộ sẽ thay thế cài đặt từ xa, 0 nghĩa là tắt
      RuleListPath: # /etc/XrayR/rulelist Đường dẫn đến tệp danh sách quy tắc cục bộ
    ControllerConfig:
      DisableSniffing: true
      ListenIP: 0.0.0.0 # Địa chỉ IP bạn muốn nghe
      SendIP: 0.0.0.0 # Địa chỉ IP bạn muốn gửi gói
      UpdatePeriodic: 60 # Thời gian cập nhật nodeinfo, bao nhiêu giây.
      EnableDNS: false # Sử dụng cấu hình DNS tùy chỉnh, Hãy đảm bảo rằng bạn đặt dns.json tốt
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, chiến lược DNS
      EnableProxyProtocol: false # Chỉ hoạt động cho WebSocket và TCP
      EnableFallback: false # Chỉ hỗ trợ cho Trojan và Vless
      FallBackConfigs:  # Hỗ trợ nhiều dự phòng
        -
          SNI: # TLS SNI (Chỉ báo tên máy chủ), trống cho bất kỳ
          Path: # HTTP PATH, trống cho bất kỳ
          Dest: 80 # Bắt buộc, Điểm đến của dự phòng, check https://xtls.github.io/config/features/fallback.html để biết chi tiết.
          ProxyProtocolVer: 0 # Gửi phiên bản giao thức PROXY, 0 cho dsable
      CertConfig:
        CertMode: http # Tùy chọn về cách lấy chứng chỉ: none, file, http, dns. Chọn "không" sẽ buộc vô hiệu hóa cấu hình tls.
        CertDomain: "xxx" # Tên miền để chứng chỉ
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Được cung cấp nếu CertMode là tệp
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # Nhà cung cấp chứng chỉ DNS, Nhận danh sách hỗ trợ đầy đủ tại đây: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # Tùy chọn DNS ENV được nhà cung cấp DNS sử dụng
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb      
